### ISSUE TITLE
Default payment selected not working as expected.

### ISSUE THREAD

**Issue by MagentoGuysProjects** [mollie/magento2-hyva-checkout#10]
I am facing one issue on Hyva checkout. We have mollie payment method installed. We have set default payment methods based on store as we have multiple stores.  Admin : https://i.imgur.com/C2Xha7Q.png
Front : https://i.imgur.com/37J0XyM.png
But it is not getting selected as default on front-end.
can any one help me with this?

Thanks,
Narayan

**Comment by Frank-Magmodules** [comment]
Hi There @MagentoGuysProjects ,

Thank you for opening this issue. Which version of the plugin are you using? Last week we released an update for this plugin that addresses exactly this issue, so I’m suspecting that you have a version from before that. 

If you have the latest version and still are experiencing this issue, could you please [contact us](https://www.magmodules.eu/help) directly so we can take a look at your setup to see what’s going on?

**Comment by Frank-Magmodules** [comment]
Hi @MagentoGuysProjects, i'm marking this as resolved as we've fixed the issue. It also seems Hyvä isn't integrated into the sample URL on the frontend (anymore). Should you have any comments or further questions, please feel free to reopen the issue.
