### ISSUE TITLE
Missing Fee Checkout

### ISSUE THREAD

**Issue by in-session** [mollie/magento2-hyva-checkout#11]
**Describe the bug**
The fees are not displayed in the checkout
https://github.com/mollie/magento2/blob/master/view/frontend/web/template/checkout/summary/payment-fee.html

**Used versions**
- *Magento Version 2.4.6-p2*
- *Open source*
- *Mollie version number 2.31.0*

**To Reproduce**
1. Go to admin > mollie > Payment Methods
2. Click on Klarna Slice > Payment Surcharge > percent + Payment Surcharge percentage > 3

**Expected behavior**
Showing an additional total segment for additional fees.
![image](https://github.com/mollie/magento2-hyva-checkout/assets/16542619/ad54b948-8237-41a2-80ac-2e11b1e1f4c4)

**Actual behavior**
Only a price increase in the Grand total without seeing why the price increases.
![image](https://github.com/mollie/magento2/assets/16542619/d61aeec2-1678-4e09-905e-1747a8152ce6)

**Comment by in-session** [comment]
Hi @Frank-Magmodules,

we first started with Hyva and thought that the function is not yet available. After the test I had seen that you have a [KO template](https://github.com/mollie/magento2/blob/master/view/frontend/web/template/checkout/summary/payment-fee.html) in the original module inside therefore I had then moved here.

Our current versions:
mollie/magento2                                                   2.31.0     
mollie/magento2-hyva-checkout                                     1.2.0      
mollie/magento2-hyva-compatibility                                2.1.0      
mollie/magento2-subscriptions                                     1.12.1     
mollie/mollie-api-php                                             v2.61.0


hyva-themes/magento2-hyva-checkout                                1.1.6

**Comment by Frank-Magmodules** [comment]
Hello @in-session, we have successfully reproduced this issue and will be releasing a new version with a fix for it shortly.

**Comment by Frank-Magmodules** [comment]
Hi There @in-session , i'm happy to share we've just fixed this issue within this [1.2.1](https://github.com/mollie/magento2-hyva-checkout/releases/tag/1.2.1) release.
Thanks again and have a good day!
