### ISSUE TITLE
BUG mollie_methods_creditcard_vault

### ISSUE THREAD

**Issue by stijntrinos** [mollie/magento2-hyva-checkout#19]
We have the Magento Vault enabled with the saved credit cards. Unfortunately there is a big bug that shows all saved credit cards in the shop. See the picture below.

![Screenshot 2024-03-06 at 09 56 19](https://github.com/mollie/magento2-hyva-checkout/assets/96116544/aef43de7-8d3b-45a8-b73c-84eae736ba47)

I found that it needs a search filter on the customer_id in
`mollie/magento2-hyva-checkout/src/Mollie_HyvaCheckout/Service/Vault/GetSavedCards.php`

**Comment by Frank-Magmodules** [comment]
Hey @stijntrinos , thanks for bringing up this issue. We’ve just rolled out a fix for it with the [latest release](https://github.com/mollie/magento2-hyva-checkout/releases).

In the original/Luma checkout, cards were rendered for us. In the Hyvä Checkout, we need to fetch and display them manually. In this process, we failed to add a filter for the customer ID, which is unfortunate. 

In the fix we just rolled out, we are now using an API from Magento Vault that takes extra parameters into account. Like when the card has expired, if it’s visible, and if it’s active.

While this unfortunate incident qualifies as a bug, it’s important to note that it’s **impossible to proceed and complete payment with any saved cards** that don’t belong to the customer during this, and no credit card details are exposed besides the last four digits and the card type.

Thanks for bringing this up @stijntrinos !

**Comment by stijntrinos** [comment]
Hi @Frank-Magmodules,
Thanks for getting on this so quickly! 
> no credit card details are exposed besides the last four digits and the card type.

Yes, I noted this, it was pure something weird for the customer that you see all the credit cards saved.
