### ISSUE TITLE
Credit Card - Mollie Components - Not all required components are mounted yet.

### ISSUE THREAD

**Issue by sprankhub** [mollie/magento2-hyva-checkout#21]
$ composer show mollie/*
    mollie/magento2               2.37.0 Mollie Payment Module for Magento 2
    mollie/magento2-hyva-checkout 1.3.2  Hyvä Themes Checkout module for Mollie Payments
    mollie/mollie-api-php         2.67.0 Mollie API client library for PHP. Mollie is a European Payment Service provider and offers international payment methods such as Mastercard, VISA, American Express and ...
    $ composer show hyva-themes/*
    hyva-themes/magento2-aheadworks-giftcard    1.0.2  Hyvä Themes Compatibility module for Aheadworks_Giftcard
    hyva-themes/magento2-compat-module-fallback 1.1.3  Allow templates to be overridden by Hyvä Themes compatibility modules without layout XML.
    hyva-themes/magento2-default-theme          1.3.5  Default Hyvä Theme
    hyva-themes/magento2-email-module           1.0.5  Hyva Themes email module
    hyva-themes/magento2-graphql-tokens         1.0.4  Adds Customer and Cart tokens to CustomerData sections
    hyva-themes/magento2-graphql-view-model     1.0.5  Provide ability to customize GraphQL queries and mutations for Hyvä themes.
    hyva-themes/magento2-hyva-checkout          1.1.16 Hyvä Themes checkout module
    hyva-themes/magento2-reset-theme            1.1.5  A theme that unsets all Magento 2 layout blocks. A real _blank_ theme.
    hyva-themes/magento2-theme-fallback         1.0.3  Allow for Hyvä Themes to fall back to regular Magento themes on specific routes.
    hyva-themes/magento2-theme-module           1.3.8  Hyva Themes companion module

Magento 2.4.6-p5

When I enable the credit card payment method and enable Mollie Components in `payment/mollie_methods_creditcard/use_components`, I cannot buy with any other payment method any more. Even if another payment method is selected and I submit the order, I get the following error message:

> Not all required components are mounted yet. Card holder, card number, expiry date, and verification code are required. 

It looks like this:

![image](https://github.com/mollie/magento2-hyva-checkout/assets/930199/d73e4ece-71b2-4efc-9b16-46fafa1d0e8d)

**Comment by Frank-Magmodules** [comment]
Hi @sprankhub, thanks for bringing up this issue mate!
I'll investigate this issue soon and get back to you.

**Comment by Frank-Magmodules** [comment]
Hi There @sprankhub, yes I have.
We've got a solution ready to roll out in the upcoming version later today!

**Comment by Frank-Magmodules** [comment]
Hey @sprankhub, [Here we go!](https://github.com/mollie/magento2-hyva-checkout/releases/tag/1.3.3)
Thanks for your patience! Have a fantastic day. Closing this issue now.
