### ISSUE TITLE
Improve error message for Billie, when no company is given

### ISSUE THREAD

**Issue by norgeindian** [mollie/magento2-hyva-checkout#25]
This issue is similar to https://github.com/mollie/magento2/issues/640
For a standard checkout, this is fixed.
But for Hyvä Checkout, you still get the following error message 

```
Error executing API call (422: Unprocessable Entity): A billing organization name is required for this payment method. Documentation: https://docs.mollie.com/reference/v2/orders-api/create-order
```
It would be awesome if this could be improved, so customers actually know, what is wrong.

**Used versions**

Magento Version number(eg 2.3.5): 2.4.5-p8
Open source/Enterprise/B2b: Open Source
Mollie version number (Check configuration): 2.37.0
Mollie Hyvä Checkout Version: 1.3.2

**To Reproduce**

- Activate Hyvä Checkout
- Put a random product into the cart
- Go to the checkout
- Do NOT enter a company in the address fields
- Try to check out via Billie

**Comment by norgeindian** [comment]
@Frank-Magmodules, as you did the fix in https://github.com/mollie/magento2/issues/640, could you fix it here as well?
That would be really awesome.

**Comment by Frank-Magmodules** [comment]
Thanks, @norgeindian! Yes, I'll make sure to include that in the upcoming release!

**Comment by norgeindian** [comment]
@Frank-Magmodules, awesome, thanks.
Do you already know, when the next release will be published?

**Comment by Frank-Magmodules** [comment]
Hi @norgeindian, I'm pleased to inform you that we've just released the new version of the Hyva Compat module! 
I'm closing this issue for now, but please feel free to comment or reopen it if needed.
