### ISSUE TITLE
524 Timeout - /checkout/onepage/success

### ISSUE THREAD

**Issue by pjw345** [mollie/magento2-hyva-checkout#28]
We are using:
- Magento 2.4.7-p2
- Hyva Checkout version 1.1.24
- Mollie for hyva checkout version 1.5.0
- Mollie for Magento version 2.41.0

After a customer has processed the payment in Mollie, they are redirected back to the success page on our site and some are experiencing very long wait times and sometimes even 524 errors that we see logged in Cloudflare.

Now we have reached out to Mollie, Cloudflare and Hypernode in a attempt to find a solution to this issue.  We didn't see this happening when we were using Stripe (which we had to stop using as there is an issue with redirecting to Paypal and 3D)

On Cloudflare we have Mollie's IP addresses whitelisted, on the server there are no ratelimiting restrictions on Mollie and we've checked out CSP policies.  There is nothing glaringly obvious and we were wondering if anybody had experienced this and found a solution

**Comment by fjbender** [comment]
We have seen some weird things with Cloudflare, but usually allowlisting our IPs solved things. I recommend you reach out in our [Developer Discord](https://discord.gg/mollie) so we can take a closer look at some examples.

**Comment by pjw345** [comment]
With the help of New Relic we were able to trace it down to the fact that during the checkout process it would appear they are running a query on the sales_order table selecting all records for a specific customer_email.

Our sales_order table has over 2 million records and the customer_email field is NOT indexed.  The simple fix was to add an index to the sales_order table for the customer_email field and the query now runs in the milliseconds, but one still has to ask why are they querying the sales_order table? 

Like I mentioned, this was not something we experienced with the Stripe module

**Comment by fjbender** [comment]
Many thanks for putting in the time and effort to do this research! Can you share the exact point where we trigger that query? I am wondering whether it's in this plugin or in mollie/magento2

**Comment by pjw345** [comment]
I suspect it is in the mollie/magento2 and not in this plugin, hence the issue can be closed here

**Comment by Frank-Magmodules** [comment]
Hi there @pjw345 ,

We haven’t seen an issue about this opened in the `mollie/magento2` repository yet. We still did some investigations, but couldn’t find a point where the Mollie extensions are selecting records based on the `customer_email`. If you really think this is an issue with the Mollie extension, would you then be so kind to share a little bit more information about your find so that we can take action on that? Thanks!

**Comment by pjw345** [comment]
Have a look at \Mollie\Payment\Service\Order\DeletePaymentReminder where they select orders based on customer_email.  As I said previously customer_email is NOT indexed on sales_order and if you have a shop like ours where we have over 2 million records in the table this will cause a problem.

**Comment by pjw345** [comment]
My solution was to alter the table and add an index to the sales_order table.  However I am sure this can also be done in Magento by creating the appropriate db_schema.xml in the Mollie module.  

    <table name="sales_order" resource="sales" comment="Sales Flat Order">
        <index referenceId="SALES_ORDER_CUSTOMER_EMAIL" indexType="btree">
            <column name="customer_email"/>
        </index>
    </table>

**Comment by Frank-Magmodules** [comment]
Hi @pjw345, good news! 
We've added this as an improvement in the upcoming release, where we no longer depend on the sales_order table in this case. I'll keep this ticket open for now, and although the fix will be included in the [main module](https://github.com/mollie/magento2), I'll follow up and close the ticket once it's released. Thanks for your patience!

**Comment by Frank-Magmodules** [comment]
We’ve released [this](https://github.com/mollie/magento2), so I’m closing the issue. Thanks again!
