### ISSUE TITLE
Pay Button Text disappears with Apple Pay

### ISSUE THREAD

**Issue by Irinina** [mollie/magento2-hyva-checkout#33]
Whenever we select Apple Pay, the "Place Order"-text on the pay button disappears. This make sense, because in `src/Mollie_HyvaCheckout/view/frontend/tailwind/tailwind-source.css` you set the font-size to 0 for the pay button (`.btn.btn-primary.apple-pay-button`). 

I can see, that in `src/Mollie_HyvaCheckout/view/frontend/templates/component/payment/method/applepay.phtml` you add three classes to the button (`apple-pay-button`, `apple-pay-button-with-text`, `apple-pay-button-black-with-text`). But only the `apple-pay-button` class has styling. 
Hence, the normal text disappears, but there is no replacement shown instead. Could you check this issue please?

**Comment by Frank-Magmodules** [comment]
Hi @Irinina,

Thank you for clearly explaining the issue. I’ll review this with the team and get back to you soon.

**Comment by Frank-Magmodules** [comment]
Hi There @Irinina , 
I’m happy to share that the fix has been officially included in the [latest release](https://github.com/mollie/magento2-hyva-checkout/releases/tag/1.5.2). I’ll go ahead and close this issue for now. Thanks again and have a great day!
