### ISSUE TITLE
mollie_methods_creditcard_vault is not working

### ISSUE THREAD

**Issue by Tjitse-E** [mollie/magento2-hyva-checkout#4]
### Steps to reproduce
1.  Install this module  (v1.1.0) and set it up
2. Activate creditcard in the checkout
3. Go to the checkout

### Expected result
There is one creditcard method.

### Actual result
There are 2 creditcard methods active in the checkout `mollie_methods_creditcard_vault` and `mollie_methods_creditcard`. The problem is this module doesn't account for  `mollie_methods_creditcard_vault` so that one will crash when you try to checkout with it.

![CleanShot 2023-08-17 at 16 12 24](https://github.com/mollie/magento2-hyva-checkout/assets/14849044/c63e38e5-7092-45d2-984e-d63cb8a342ff)

**Comment by Tjitse-E** [comment]
Setting `payment/mollie_general/enable_magento_vault` hides the Vault payment method, but maybe we should account for it in the Hyvä checkout compatibility module since it's not yet implemented (right?).

**Comment by Frank-Magmodules** [comment]
Thank you for opening this issue @Tjitse-E , we'll look into your concern and provide a response shortly.

**Comment by Frank-Magmodules** [comment]
Hello @Tjitse-E! I'm thrilled to inform you that our latest release, available [here](https://github.com/mollie/magento2-hyva-checkout/releases), is now compatible with Magento Vault. We appreciate you bringing this to our attention. I'm closing this issue for the time being, but please don't hesitate to reopen it or respond if you encounter any further issues. Thank you!
