### ISSUE TITLE
Hiding apple pay after payment with javascript is bad practice

### ISSUE THREAD

**Issue by jeroenbalk-adwise** [mollie/magento2-hyva-checkout#5]
In vendor/mollie/magento2-hyva-checkout/src/Mollie_HyvaCheckout/view/frontend/templates/component/payment/method/applepay_after.phtml

there are some checks to validate if apple pay can be used and conditionally puts a display none on applepay method. This seems like a bad practice. Checks should be done in a different way so the array with available payment methods can be updated, and a refresh can be emitted on the magewire Payment MethodList.

The current 'quickfix' makes it more difficult to correctly tweak and style the checkout because pseudo classes like nth-child, odd/even can't be used correctly.

**Comment by Frank-Magmodules** [comment]
Greetings, @jeroenbalk-adwise,

Could you please elaborate a bit more on the “Checks should be done in a different way” part? The issue with Apple Pay is that it can’t be checked server side, as far as we are aware. This forces us to hide the method using the tools available in the frontend.

**Comment by Frank-Magmodules** [comment]
Hello @jeroenbalk-adwise, since there hasn't been a response regarding this matter, I will temporarily close this issue. If it remains important to you, please feel free to reopen it or create a new issue.
